/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>



void delay(uint32_t d)

{

    for(uint32_t i=0;i<d;i++)

    {

        for(uint32_t i=0;i<d;i++);

    }

}

int main(void)

{

    uint32_t *pcntreg = (uint32_t *)0x4002104c;

    uint32_t *modereg = (uint32_t *)0x48000000;

    uint32_t *poutreg = (uint32_t *)0x48000014;



    *pcntreg |=1;



    *modereg &=~(3<<10);

    *modereg |=(1<<10);



    while(1)

    {



        *poutreg |=(1<<5);

        delay(500);

        *poutreg &= ~(1<<5);

        delay(500);

    }





}
